### ISSUE TITLE
Help on package <3

### ISSUE THREAD

**Issue by Wjplatformer** [Wjplatformer/Authenticlick#3]
Hellow @LogSkele , you've offered help to me. So, yep, I need help. When I went to the PyPi [tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/) on making a package, they asked me to choose from 4 build systems. I have not built a system in my life so would you give me an explanation on which is the best and why? 
![image](https://user-images.githubusercontent.com/82447031/175499012-1d3c144f-1bc7-40bc-976c-908fb7d4b4d5.png)
Also, erm metadata help?
![image](https://user-images.githubusercontent.com/82447031/175499991-96dd954e-aab9-4536-b14d-a48c58b6677c.png)

**Comment by iop3** [comment]
AHaha I see do you use vs code?

**Comment by iop3** [comment]
Just copy my gitcollect and change things. xD

**Comment by iop3** [comment]
You have to first create a pypi account

**Comment by Wjplatformer** [comment]
done :) . I trust you on copying gitcollect things :+1:
